### ISSUE TITLE
migrate tags script results in error

### ISSUE THREAD

**Issue by kalpitad** [StephenHynes7/le_utils#18]
I get the following error, when I run the script:
`python le_migrate_tags.py ACCOUNT_KEY import cloudtrail.txt`

Error:
```
Traceback (most recent call last):
  File "le_migrate_tags.py", line 5, in <module>
    import requests
ImportError: No module named requests
```

Is this indeed an error in the script, or am I doing something wrong? Thanks!

**Comment by mrud** [comment]
You have to have the [requests module](http://docs.python-requests.org/en/latest/) module installed.

If you are on Debian you can just run `apt-get install python-requests`

**Comment by StephenHynes7** [comment]
I would recommend using https://community.logentries.com/packs/aws-cloudtrail/ community pack for importing Tags,Searches and Dashboards. See here https://logentries.com/doc/community-packs/#import

**Comment by kalpitad** [comment]
This worked for me, thanks!
